# Generated by Django 3.1.5 on 2021-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_things_I_buy', '0002_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
