# Generated by Django 3.1.5 on 2021-01-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_things_I_buy', '0003_product_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customized_prod',
            field=models.BooleanField(default=True),
        ),
    ]
